import Link from 'next/link'

const S = {
 brand: '#0F766E', brandLight: '#14B8A6', brandFaded: '#F0FDFA', brandBorder: '#99F6E4',
 n50: '#FAFAF9', n100: '#F5F5F4', n200: '#E7E5E4', n400: '#A8A29E', n500: '#78716C',
 n700: '#44403C', n800: '#292524', n900: '#1C1917', white: '#FFFFFF',
 amber: '#D97706', amberBg: '#FFFBEB', amberBdr: '#FDE68A',
 headerBg: '#0C1F1C', font: "'DM Sans', sans-serif",
}

export default function DisclaimerPage() {
 return (
    <>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
   <div style={{ minHeight: '100vh', background: S.n50, fontFamily: S.font }}>

    <div style={{ background: S.headerBg, padding: '60px 24px 48px', textAlign: 'center' }}>
     <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, textDecoration: 'none', marginBottom: 32 }}>
      <div style={{ width: 28, height: 28, borderRadius: 8, background: `linear-gradient(135deg,${S.brand},${S.brandLight})`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: 900, fontSize: 13 }}><img src="/logo-mark.svg" alt="" style={{ width: '13px', height: '13px' }} /></div>
      <span style={{ fontWeight: 800, fontSize: 15, color: '#F9FAFB', letterSpacing: '-0.02em' }}>Locatalyze</span>
     </Link>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: 'rgba(15,118,110,0.15)', border: '1px solid rgba(15,118,110,0.3)', borderRadius: 20, padding: '4px 12px', fontSize: 11, fontWeight: 700, color: S.brandLight, letterSpacing: '1px', textTransform: 'uppercase', marginBottom: 16 }}>Legal</div>
     <h1 style={{ fontSize: '36px', fontWeight: 800, color: '#F9FAFB', letterSpacing: '-0.5px', marginBottom: 12 }}>Disclaimer</h1>
     <p style={{ fontSize: 13, color: '#6B7280' }}>Last updated: 1 March 2026</p>
    </div>

        <div style={{ maxWidth: 760, margin: '0 auto', padding: '48px 24px 80px' }}>

     {/* Warning box */}
          <div style={{ background: S.amberBg, border: `1.5px solid ${S.amberBdr}`, borderRadius: 14, padding: '20px 24px', marginBottom: 40 }}>
      <p style={{ fontSize: 14, fontWeight: 700, color: S.amber, marginBottom: 8 }}> Important notice</p>
            <p style={{ fontSize: 14, color: '#92400E', lineHeight: 1.75 }}>
       Locatalyze provides <strong>indicative analysis only</strong>. Reports generated by this platform are not financial advice, investment advice, legal advice, or a guarantee of business viability. You must conduct your own due diligence and consult qualified professionals before making any business or financial decisions.
            </p>
          </div>

          {[
            {
              title: '1. General information only',
       body: `All content, reports, scores, verdicts and financial projections produced by Locatalyze (operated by Locatalyze Pty Ltd, ABN pending) are provided for general informational purposes only. Nothing on this platform constitutes financial product advice, investment advice, real estate advice, legal advice or any other form of professional advice.\n\nLocatalyze is not a licensed financial adviser, real estate agent, business broker or valuer. The GO / CAUTION / NO verdict is an automated output based on data inputs and a scoring algorithm — it is not a professional recommendation.`,
            },
            {
              title: '2. No guarantee of accuracy',
       body: `While we make reasonable efforts to ensure the accuracy of the data used in our analyses, we do not warrant that:\n\n• Competitor data is complete or current\n• Demographic figures reflect current conditions\n• Rent benchmarks match actual available commercial rents\n• Financial projections will be achieved\n• Any suburb or location score is free from error\n\nData sources include OpenStreetMap, ABS Census (various years), Geoapify, and AI-generated estimates. These may be outdated, incomplete or inaccurate for your specific circumstances.`,
            },
            {
              title: '3. Not a substitute for professional advice',
       body: `Before signing any commercial lease or making any significant business investment, you should obtain independent advice from:\n\n• A licensed commercial real estate agent\n• A qualified accountant or business advisor\n• A solicitor familiar with commercial leasing law in your state\n• An industry-specific consultant where relevant\n\nLocatalyze reports are a starting point for research — not a substitute for professional due diligence.`,
            },
            {
              title: '4. Limitation of liability',
       body: `To the maximum extent permitted by the Australian Consumer Law and other applicable legislation, Locatalyze excludes all liability for any loss or damage (including consequential loss, loss of profit, loss of opportunity, financial loss or any indirect loss) arising from:\n\n• Reliance on any report, score, verdict or content produced by the platform\n• Errors or omissions in the underlying data\n• Business decisions made using our outputs\n• Inaccuracies in AI-generated content\n\nOur liability for any non-excludable guarantees under the Australian Consumer Law is limited to re-supplying the relevant service or refunding the price paid, at our election.`,
            },
            {
              title: '5. External data sources',
       body: `Our analyses incorporate data from third-party sources including OpenStreetMap contributors, the Australian Bureau of Statistics, Geoapify, Nominatim, and others. We are not responsible for the accuracy of third-party data and do not endorse any third-party service.`,
            },
            {
              title: '6. AI-generated content',
       body: `Reports include content generated by large language model AI (OpenAI GPT-4o-mini). AI-generated content may contain errors, hallucinations or inaccuracies. All AI-generated narrative, SWOT analysis and recommendations should be treated as illustrative only and independently verified before being relied upon.`,
            },
            {
              title: '7. Changes to this disclaimer',
       body: `We may update this disclaimer from time to time. The date at the top of this page indicates when it was last revised. Continued use of the platform after changes constitutes acceptance of the updated disclaimer.`,
            },
            {
              title: '8. Contact',
       body: `If you have questions about this disclaimer, contact us at hello@locatalyze.com.au.`,
            },
          ].map(section => (
            <div key={section.title} style={{ marginBottom: 36 }}>
              <h2 style={{ fontSize: 17, fontWeight: 700, color: S.n900, marginBottom: 10 }}>{section.title}</h2>
              <div style={{ fontSize: 14, color: S.n500, lineHeight: 1.85, whiteSpace: 'pre-line' }}>{section.body}</div>
      </div>
          ))}

          <div style={{ borderTop: `1px solid ${S.n200}`, paddingTop: 28, display: 'flex', gap: 20, flexWrap: 'wrap' }}>
      <Link href="/terms"  style={{ fontSize: 13, color: S.brand, fontWeight: 600, textDecoration: 'none' }}>Terms of Service</Link>
      <Link href="/privacy" style={{ fontSize: 13, color: S.brand, fontWeight: 600, textDecoration: 'none' }}>Privacy Policy</Link>
      <Link href="/contact" style={{ fontSize: 13, color: S.brand, fontWeight: 600, textDecoration: 'none' }}>Contact Us</Link>
     </div>
        </div>
      </div>
    </>
  )
}