const fs = require('fs')

const newPosts = `
  // ─── POST 31 ─────────────────────────────────────────────────────────────────
  'how-to-choose-cafe-location-australia': {
    slug: 'how-to-choose-cafe-location-australia',
    title: 'How to Choose a Café Location in Australia (2026 Guide)',
    seoTitle: 'How to Choose a Café Location in Australia 2026',
    metaDescription: 'How to choose a café location in Australia: foot traffic benchmarks, rent ratios, competitor thresholds and suburb demographics — a complete data-driven guide.',
    primaryKeyword: 'how to choose a café location in Australia',
    secondaryKeywords: ['café location analysis', 'best café locations Australia', 'opening a café Australia', 'café feasibility', 'café foot traffic'],
    category: 'Cafes', date: 'March 10, 2026', readTime: '10 min read',
    heroImg: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=1200&q=85',
    tags: ['Location strategy', 'Cafes', 'Australia'],
    intro: 'Choosing a café location in Australia is the single highest-stakes decision you will make. Get it wrong and no amount of great coffee, beautiful fit-out or loyal Instagram following will save you. Get it right and even an average product can survive. This guide gives you a framework to evaluate any address before you sign anything.',
    sections: [
      { type: 'stats', items: [{ value: '60%', label: 'Of café failures attributed to poor location choice' }, { value: '$85K', label: 'Average Australian café fit-out cost' }, { value: '8–12%', label: 'Target rent-to-revenue ratio for viability' }] },
      { type: 'h2', text: 'Start with the rent-to-revenue ratio, not the fit-out' },
      { type: 'p', text: 'Most aspiring café owners start by calculating fit-out costs. The smarter move is to start with the rent. Rent is fixed. Revenue is variable. If your rent sits above 15% of your revenue, you are fighting gravity every single month.' },
      { type: 'p', text: 'The formula: monthly rent ÷ 0.10 = the monthly revenue you need to keep rent at 10%. Divide by your average transaction value. Divide by 26 trading days. That is your required daily transaction count. Run this number before you visit a single site.' },
      { type: 'callout', icon: '🧮', title: 'Quick rent viability test', body: 'Monthly rent: $5,000\\nTarget rent ratio: 10%\\nRequired monthly revenue: $50,000\\nAverage transaction: $8.50\\nRequired daily transactions: 226\\n\\nIf 226 transactions per day seems unrealistic at this location — it probably is.', variant: 'amber' },
      { type: 'h2', text: 'Foot traffic: the number that overrides everything else' },
      { type: 'p', text: 'Every other metric is secondary to foot traffic past your front door at the times you are open. A café that relies on destination traffic — where people specifically plan to visit — is a different and much harder business than one that captures walk-past customers.' },
      { type: 'p', text: 'Stand at the location at 7:30am on a Tuesday for 10 minutes. Count every person who walks past. Multiply by 6 for an hourly rate. Do this again at 12pm and 3pm. The pattern tells you your revenue ceiling and peak staffing requirements before you have spent a cent.' },
      { type: 'list', heading: 'Foot traffic benchmarks for cafes', items: ['Under 40/hour: Very high risk. Only viable with extreme low rent or destination concept.', '40–80/hour: Moderate. Viable with competitive rent and strong execution.', '80–150/hour: Good. Location has genuine commercial potential.', '150+/hour: Strong. Focus shifts to lease terms and competition density.'] },
      { type: 'h2', text: 'How to read competition correctly' },
      { type: 'p', text: 'Two or three cafés nearby is often a green flag, not a red one. It signals that the local population already has the habit of buying coffee out — you are tapping into existing demand rather than trying to create it. Zero competition in a busy area can signal untapped opportunity, but it can also signal that others have tried and failed.' },
      { type: 'p', text: 'The danger zone is 6 or more cafés within 300 metres without exceptional foot traffic to support them all. In that scenario you need a clear differentiator — a specific niche, dramatically faster service, a unique price point, or a captive audience like being inside an office building or gym.' },
      { type: 'h2', text: 'Demographics: who is actually walking past' },
      { type: 'p', text: 'Not all foot traffic converts to café revenue equally. Office workers on a commute spend differently to weekend tourists. Families with prams have different dwell time to solo laptop workers. The demographic profile of the surrounding suburb tells you the likely shape of your customer base.' },
      { type: 'callout', icon: '📊', title: 'Demographics of a high-converting café catchment', body: 'Median household income: $85,000+\\nAge concentration: 25–45\\nEmployment: high proportion full-time workers\\nHousing: mix of apartments and terrace houses\\nProximity: within 400m of train station, offices or gym precinct', variant: 'green' },
      { type: 'h2', text: 'The suburb shortlist method' },
      { type: 'p', text: 'Rather than evaluating individual sites in isolation, start by shortlisting 4–6 suburbs that meet your demographic and foot traffic criteria. Then identify available sites within those suburbs. This reverses the typical process of falling in love with a site then rationalising it, and keeps you data-led.' },
      { type: 'p', text: 'Tools like Locatalyze let you run a full location analysis on any Australian address in under 60 seconds — competitor count, demographic profile, and a GO/CAUTION/NO verdict. Run it on every suburb on your list before visiting a single one.' },
      { type: 'h2', text: 'Physical site checklist before you sign' },
      { type: 'numbered', heading: 'Non-negotiables to verify in person', items: ['Corner or end-of-row position for dual-direction visibility', 'Existing grease trap and commercial kitchen infrastructure', 'North or east-facing outdoor seating for morning trade', 'Width of footpath — can a queue form without blocking pedestrians?', 'Rear access for deliveries during service hours', 'Power capacity for commercial coffee equipment (3-phase preferred)'] },
      { type: 'h2', text: 'FAQ: choosing a café location in Australia' },
      { type: 'h3', text: 'What is the most important factor when choosing a café location?' },
      { type: 'p', text: 'Foot traffic volume during your trading hours, combined with a rent-to-revenue ratio below 12%. These two factors predict viability more reliably than any other variable.' },
      { type: 'h3', text: 'How much foot traffic does a café need to be viable?' },
      { type: 'p', text: 'A minimum of 60 pedestrians per hour past the front door during your peak trading window is a reasonable baseline for a standard 40-seat café with average transaction values around $8–10.' },
      { type: 'h3', text: 'Should I avoid locations with other cafés nearby?' },
      { type: 'p', text: 'Not necessarily. Two to four competitors within 300 metres indicates proven local demand. More than six is a warning sign unless foot traffic is genuinely exceptional. Zero competitors warrants investigation — it may mean low demand rather than untapped opportunity.' },
    ],
  },

  // ─── POST 32 ─────────────────────────────────────────────────────────────────
  'business-feasibility-study-template-australia': {
    slug: 'business-feasibility-study-template-australia',
    title: 'Business Feasibility Study Template Australia (Free Framework 2026)',
    seoTitle: 'Business Feasibility Study Template Australia 2026',
    metaDescription: 'A practical business feasibility study template for Australian entrepreneurs. Covers location analysis, revenue modelling, competitor assessment and go/no-go criteria.',
    primaryKeyword: 'business feasibility study template Australia',
    secondaryKeywords: ['feasibility study Australia', 'business location feasibility', 'small business feasibility template', 'how to do a feasibility study', 'feasibility report Australia'],
    category: 'Planning', date: 'March 8, 2026', readTime: '11 min read',
    heroImg: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=85',
    tags: ['Feasibility', 'Planning', 'Australia'],
    intro: 'A feasibility study is the document that separates founders who make informed decisions from those who make expensive ones. Most templates you will find online are either too generic to be useful or so complex they require a consultant to complete. This is a practical, location-focused feasibility framework built specifically for Australian retail and hospitality businesses.',
    sections: [
      { type: 'stats', items: [{ value: '42%', label: 'Of small businesses fail in first 3 years (ABS)' }, { value: '$340K+', label: 'Average cost of a failed commercial lease' }, { value: '30s', label: 'Time to run an AI location feasibility check' }] },
      { type: 'h2', text: 'What a feasibility study actually needs to answer' },
      { type: 'p', text: 'A feasibility study for a location-dependent business needs to answer four questions: Is there enough demand in this location for what I am selling? Can I price my product to generate a viable margin after rent? Is the competition manageable? And do the demographics of the area match my target customer?' },
      { type: 'p', text: 'Everything else — branding, website, equipment choices, staffing structure — is secondary to these four. They are the questions a business feasibility study exists to answer, and the answers need to be grounded in data, not optimism.' },
      { type: 'h2', text: 'Section 1: Location analysis' },
      { type: 'p', text: 'This is the most important section and the one most commonly skipped or completed superficially. Location analysis must cover three components: foot traffic volume, competitor proximity, and demographic fit.' },
      { type: 'callout', icon: '📍', title: 'Location analysis checklist', body: 'Foot traffic count: peak hour pedestrians past front door\\nCompetitor count: direct competitors within 300m and 500m\\nCompetitor quality: are they well-established or vulnerable?\\nDemographic match: do suburb income/age data match your target customer?\\nVisibility: is the site visible from the street at 20 metres?\\nAnchor proximity: what high-traffic draws are within 200m?', variant: 'teal' },
      { type: 'h2', text: 'Section 2: Revenue model' },
      { type: 'p', text: 'Build your revenue model from the bottom up, not the top down. Do not start with "we expect to capture 5% of the market." Start with: how many transactions per day at what average value, and is that achievable at this specific location?' },
      { type: 'numbered', heading: 'Bottom-up revenue model steps', items: ['Count or estimate daily foot traffic past the site', 'Apply a realistic capture rate (1–5% for new businesses)', 'Multiply by average transaction value for your category', 'Multiply by trading days per month', 'Subtract COGS (typically 25–35% for food, 50–60% for retail)', 'Subtract fixed costs: rent, labour, utilities, insurance', 'The remainder is your operating margin — target 10–20%'] },
      { type: 'h2', text: 'Section 3: Competitor assessment' },
      { type: 'p', text: 'List every direct competitor within 500 metres. For each one, record: how long they have been trading, their Google rating, their approximate price point, and their apparent busiest hours. A competitor that has traded for 8 years with a 4.7 rating is a different competitive challenge than one that opened 6 months ago with mixed reviews.' },
      { type: 'h2', text: 'Section 4: Rent and lease assessment' },
      { type: 'p', text: 'Your feasibility study must include a rent stress test. Model three scenarios: base case (expected revenue), downside case (30% below expected for the first 6 months), and worst case (50% below expected). At each scenario, is the business still solvent? If the worst case means defaulting on rent within 90 days, the lease terms need to be negotiated before you sign.' },
      { type: 'callout', icon: '⚠️', title: 'Red flags in a lease assessment', body: 'Rent above 15% of projected base-case revenue\\nNo rent-free fit-out period offered\\nPersonal guarantees beyond 12 months\\nNo ability to sublease or assign\\nAnnual rent increases above CPI\\nLease term under 3 years (limits goodwill value)', variant: 'red' },
      { type: 'h2', text: 'Section 5: Go / No-Go criteria' },
      { type: 'p', text: 'Define your go/no-go criteria before you start evaluating sites. Writing them down before you fall in love with a location is the only way to apply them honestly.' },
      { type: 'list', heading: 'Example go/no-go criteria', items: ['GO: Foot traffic above 80/hour peak, rent below 12% of conservative revenue, under 4 direct competitors within 300m', 'CAUTION: One or two criteria marginally outside target — proceed only with negotiated lease protection', 'NO: Rent above 15% of conservative revenue, or foot traffic below 40/hour, or 6+ direct competitors'] },
      { type: 'h2', text: 'FAQ: business feasibility studies in Australia' },
      { type: 'h3', text: 'Do I need a professional consultant to complete a feasibility study?' },
      { type: 'p', text: 'For most small businesses, no. A structured self-completed feasibility study using publicly available data and AI tools is sufficient to make an informed go/no-go decision. Consultants add value for complex multi-site rollouts or franchise territory assessments.' },
      { type: 'h3', text: 'How long does a business feasibility study take?' },
      { type: 'p', text: 'A thorough self-completed feasibility study for a single location typically takes 3–5 business days: 1 day for location analysis, 1 day for revenue modelling, 1 day for competitor research, and 1–2 days for lease assessment and financial stress testing.' },
      { type: 'h3', text: 'What is the difference between a feasibility study and a business plan?' },
      { type: 'p', text: 'A feasibility study answers "should we do this?" A business plan answers "how will we do this?" The feasibility study comes first. Writing a business plan before completing a feasibility study is doing the work in the wrong order.' },
    ],
  },

  // ─── POST 33 ─────────────────────────────────────────────────────────────────
  'commercial-rent-affordability-calculator-australia': {
    slug: 'commercial-rent-affordability-calculator-australia',
    title: 'Commercial Rent Affordability: How to Know What You Can Afford (Australia)',
    seoTitle: 'Commercial Rent Affordability Calculator Australia 2026',
    metaDescription: 'Calculate what commercial rent you can actually afford in Australia. Rent-to-revenue ratios, break-even analysis, and suburb rent benchmarks for retail and hospitality.',
    primaryKeyword: 'commercial rent affordability calculator Australia',
    secondaryKeywords: ['commercial rent Australia', 'rent to revenue ratio', 'how much rent can my business afford', 'retail rent Australia', 'hospitality rent benchmarks'],
    category: 'Finance', date: 'March 6, 2026', readTime: '9 min read',
    heroImg: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=85',
    tags: ['Rent', 'Finance', 'Planning'],
    intro: 'The most common reason Australian small businesses fail is not bad product, bad marketing, or bad management. It is rent they could not afford from day one. Understanding commercial rent affordability before you sign a lease is not optional — it is the foundational act of business planning.',
    sections: [
      { type: 'stats', items: [{ value: '8–12%', label: 'Healthy rent-to-revenue ratio (retail/hospitality)' }, { value: '>15%', label: 'Danger zone — high failure risk' }, { value: '$340K+', label: 'Average cost of a failed 3-year commercial lease' }] },
      { type: 'h2', text: 'The rent-to-revenue ratio: the only number that matters' },
      { type: 'p', text: 'Commercial rent affordability is not about how much rent you pay in absolute terms — it is about what percentage of your revenue goes to rent. A $3,000/month rent is crippling for a business turning over $15,000/month and comfortable for one turning over $50,000/month.' },
      { type: 'p', text: 'The industry benchmark for Australian retail and hospitality businesses is 8–12% of gross revenue. Above 12% requires exceptional margins to remain viable. Above 15% is statistically dangerous. Above 20% is where businesses typically fail within 24 months regardless of other factors.' },
      { type: 'h2', text: 'How to calculate your maximum affordable rent' },
      { type: 'numbered', heading: 'Maximum rent calculation', items: ['Estimate your conservative monthly revenue (use foot traffic × realistic capture rate × average transaction)', 'Multiply by 0.10 to get your 10% rent target', 'Multiply by 0.12 to get your absolute maximum at 12%', 'Any lease with rent above this maximum should be rejected or renegotiated', 'Build in a 6-month ramp-up period where revenue may be 40–60% of target'] },
      { type: 'callout', icon: '🧮', title: 'Worked example: café in inner Melbourne', body: 'Daily foot traffic past site: 120/hour peak\\nEstimated capture rate: 3%\\nTransactions per hour: 3.6 → 25/day (7hr trading)\\nAverage transaction: $9.50\\nDaily revenue: $237.50\\nMonthly revenue (26 days): $6,175\\n\\n10% rent target: $617/month\\n12% absolute max: $741/month\\n\\nIf the asking rent is $3,500/month — this site will fail.', variant: 'amber' },
      { type: 'h2', text: 'Australian commercial rent benchmarks by category (2026)' },
      { type: 'table', headers: ['Category', 'CBD ($/m²/yr)', 'Inner suburbs', 'Outer suburbs'], rows: [['Café/coffee', '$600–1,400', '$350–700', '$180–380'], ['Restaurant', '$500–1,200', '$300–650', '$160–320'], ['Retail (fashion)', '$800–2,500', '$400–900', '$200–450'], ['Gym/fitness', '$200–500', '$150–350', '$100–250'], ['Pharmacy', '$600–1,500', '$350–700', '$200–400']] },
      { type: 'h2', text: 'Lease structure matters as much as the rent figure' },
      { type: 'p', text: 'The headline rent figure is only part of the affordability equation. Outgoings, fit-out contribution from the landlord, rent-free periods, and annual escalation clauses all affect the true cost of a lease over its term.' },
      { type: 'callout', icon: '📋', title: 'True cost of lease checklist', body: 'Base rent + estimated outgoings = gross occupancy cost\\nRent-free period: reduces effective annual cost\\nLandlord fit-out contribution: reduces capital requirement\\nAnnual rent increase: CPI is acceptable, fixed % above 3% is not\\nPersonal guarantee: limit to 6–12 months where possible\\nBreak clause: negotiate a 12-month break option at year 2 or 3', variant: 'teal' },
      { type: 'h2', text: 'FAQ: commercial rent in Australia' },
      { type: 'h3', text: 'What is a good rent-to-revenue ratio for a café in Australia?' },
      { type: 'p', text: 'Eight to twelve percent is the healthy target range. Many successful independent cafés in Sydney and Melbourne operate between 9–11%. Below 8% is excellent. Above 13–14% requires careful margin management and is not sustainable long-term for most operators.' },
      { type: 'h3', text: 'Can I negotiate commercial rent in Australia?' },
      { type: 'p', text: 'Yes, and you should. Particularly in the current market, landlords often have more flexibility than they initially indicate. Rent-free periods, fit-out contributions, capped annual increases, and break clauses are all negotiable.' },
      { type: 'h3', text: 'What happens if my business cannot pay rent?' },
      { type: 'p', text: 'In Australia, commercial leases typically allow landlords to issue a breach notice after 14 days of missed rent. If not remedied, they may re-enter the premises and pursue the tenant for remaining lease obligations. Personal guarantees mean this liability can follow you personally.' },
    ],
  },

  // ─── POST 34 ─────────────────────────────────────────────────────────────────
  'best-suburbs-open-cafe-melbourne': {
    slug: 'best-suburbs-open-cafe-melbourne',
    title: 'Best Suburbs to Open a Café in Melbourne (2026 Data)',
    seoTitle: 'Best Suburbs to Open a Café in Melbourne 2026',
    metaDescription: 'The best Melbourne suburbs to open a café in 2026, ranked by foot traffic, competition density, demographics and rent. Data-driven analysis of 15 suburbs.',
    primaryKeyword: 'best suburbs to open a café in Melbourne',
    secondaryKeywords: ['Melbourne café locations', 'open a café Melbourne', 'Melbourne café market 2026', 'café location Melbourne', 'best inner suburbs Melbourne café'],
    category: 'Melbourne', date: 'March 5, 2026', readTime: '10 min read',
    heroImg: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=1200&q=85',
    tags: ['Melbourne', 'Cafes', 'Suburb analysis'],
    intro: 'Melbourne has more cafés per capita than almost any city in the world. That makes choosing the right suburb critical — the difference between a location with genuine commercial potential and one that is already oversaturated is not always obvious from the street. This analysis looks at 15 Melbourne suburbs through the lens of foot traffic, competition, demographics and rent.',
    sections: [
      { type: 'stats', items: [{ value: '4,200+', label: 'Cafés operating in Greater Melbourne' }, { value: '18%', label: 'Of Melbourne cafés close within 2 years' }, { value: '$420K', label: 'Average median household income, top café suburbs' }] },
      { type: 'h2', text: 'What makes a great Melbourne café suburb' },
      { type: 'p', text: 'Melbourne café culture is genuinely different from the rest of Australia. The city has an established culture of all-day café trading that extends beyond the morning commute into lunch and afternoon sessions. This means suburb selection criteria are slightly different here — dwell time, a mix of workers and residents, and a population that values coffee quality all matter more than in other cities.' },
      { type: 'h2', text: 'Fitzroy and Collingwood: established but competitive' },
      { type: 'p', text: 'These inner-north suburbs have among the highest café density in Australia. Smith Street and Brunswick Street are genuinely oversaturated in some blocks — 6–9 cafés within 200 metres is common. The foot traffic is real, the demographic is right, but the competition intensity means a new entrant needs a clear point of difference and a well-negotiated lease.' },
      { type: 'callout', icon: '📊', title: 'Fitzroy/Collingwood snapshot', body: 'Foot traffic: HIGH (inner city, dense residential)\\nCompetition density: VERY HIGH (5–9 per block)\\nMedian household income: $75,000–$82,000\\nRent: $450–$750/m²/yr\\nVerdict: CAUTION — needs strong differentiation', variant: 'amber' },
      { type: 'h2', text: 'Prahran and South Yarra: premium spend, manageable competition' },
      { type: 'p', text: 'Chapel Street has suffered retail attrition over the past decade but is showing signs of recovery, particularly in the Windsor end. The residential demographic around Prahran and South Yarra is strong — median household income above $100,000 — and the café competition, while present, is more manageable than Fitzroy.' },
      { type: 'callout', icon: '📊', title: 'Prahran/South Yarra snapshot', body: 'Foot traffic: MEDIUM-HIGH (weekend strong, weekday variable)\\nCompetition density: MEDIUM (3–5 per precinct)\\nMedian household income: $105,000–$115,000\\nRent: $400–$700/m²/yr\\nVerdict: GO — strong demographics, manageable competition', variant: 'green' },
      { type: 'h2', text: 'Northcote and Thornbury: emerging opportunities' },
      { type: 'p', text: 'High Street Northcote and the southern end of High Street Thornbury are worth serious consideration. Foot traffic is strong, the demographic is right, competition is still manageable, and rents are lower than inner-north equivalents. These suburbs are 3–5 years behind Fitzroy in the gentrification curve.' },
      { type: 'callout', icon: '📊', title: 'Northcote/Thornbury snapshot', body: 'Foot traffic: MEDIUM-HIGH (strong weekend, growing weekday)\\nCompetition density: MEDIUM (3–4 per precinct)\\nMedian household income: $78,000–$82,000\\nRent: $300–$500/m²/yr\\nVerdict: GO — better value than inner north with strong fundamentals', variant: 'green' },
      { type: 'h2', text: 'Suburbs to approach with caution' },
      { type: 'list', heading: 'Melbourne suburbs with current over-supply risk', items: ['Fitzroy North on Rathdowne St: high quality but 7+ cafés in a short strip', 'St Kilda Acland Street: struggling foot traffic, high rents remain', 'Richmond Bridge Road: oversupplied, rent has not corrected relative to foot traffic', 'Box Hill Centro area: high competition, demographic mismatch for premium pricing'] },
      { type: 'h2', text: 'FAQ: opening a café in Melbourne' },
      { type: 'h3', text: 'Which Melbourne suburb has the best café opportunity in 2026?' },
      { type: 'p', text: 'Based on the balance of foot traffic, demographics, manageable competition and reasonable rent, Northcote, Thornbury, and the Windsor end of Prahran currently represent the strongest combination of factors for a new café entrant.' },
      { type: 'h3', text: 'What does it cost to open a café in Melbourne?' },
      { type: 'p', text: 'A standard 40-seat fitout in Melbourne costs $120,000–$220,000 depending on whether the space has existing kitchen infrastructure. Equipment adds $40,000–$80,000. Working capital for 6 months adds $60,000–$100,000. Total capital requirement: $220,000–$400,000.' },
    ],
  },

  // ─── POST 35 ─────────────────────────────────────────────────────────────────
  'opening-restaurant-location-analysis-guide': {
    slug: 'opening-restaurant-location-analysis-guide',
    title: 'Opening a Restaurant: The Location Analysis Guide for Australia (2026)',
    seoTitle: 'Opening a Restaurant Location Analysis Guide Australia 2026',
    metaDescription: 'A complete location analysis guide for opening a restaurant in Australia. How to assess foot traffic, competition, demographics and rent before signing your lease.',
    primaryKeyword: 'opening a restaurant location analysis',
    secondaryKeywords: ['restaurant location guide Australia', 'how to choose restaurant location', 'restaurant feasibility Australia', 'best location to open restaurant', 'restaurant site selection'],
    category: 'Restaurants', date: 'March 3, 2026', readTime: '11 min read',
    heroImg: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=85',
    tags: ['Restaurants', 'Location strategy', 'Australia'],
    intro: 'A restaurant is one of the most capital-intensive small businesses you can open in Australia. Fit-out costs of $200,000–$600,000 are common. Lease terms of 5–10 years are standard. This means the location decision is not just the most important choice you make — it is one you will live with for the entire first chapter of your business.',
    sections: [
      { type: 'stats', items: [{ value: '60%', label: 'Of restaurants close within 5 years' }, { value: '$380K', label: 'Average Australian restaurant fit-out cost' }, { value: '8–10%', label: 'Target rent-to-revenue ratio for restaurants' }] },
      { type: 'h2', text: 'Why restaurant location analysis is different from café analysis' },
      { type: 'p', text: 'Restaurants trade on different dynamics to cafés. Where a café depends heavily on commuter foot traffic during narrow morning windows, a restaurant revenue is more spread across lunch and dinner sessions, more dependent on destination traffic and less on walk-past volume. This changes how you evaluate a location.' },
      { type: 'p', text: 'For restaurants, visibility and accessibility matter more than raw pedestrian counts. Parking proximity, public transport access, and whether the suburb has an established restaurant culture are often more predictive of success than street-level foot traffic alone.' },
      { type: 'h2', text: 'The four location types and which suits your concept' },
      { type: 'list', heading: 'Restaurant location types', items: ['High street dining strip: consistent foot traffic, established dining culture, higher rents, strong competition. Best for established concepts.', 'CBD lunch market: high weekday lunch volume, low weekend trade, very high rent. Best for quick-service with high turnover.', 'Neighbourhood local: lower rent, loyal repeat customer base, limited exposure to new customers. Best for owner-operated casual dining.', 'Destination restaurant: minimal walk-past reliance, premium positioning, requires significant marketing investment. Best for chefs with an existing following.'] },
      { type: 'h2', text: 'Foot traffic for restaurants: what you are actually measuring' },
      { type: 'callout', icon: '🕐', title: 'When to count foot traffic for a restaurant', body: 'Tuesday 12:00–2:00pm: Weekday lunch benchmark\\nThursday 6:30–8:30pm: Weekday dinner benchmark\\nSaturday 12:00–2:00pm: Weekend lunch benchmark\\nSaturday 6:30–8:30pm: Weekend dinner benchmark\\n\\nVisit on at least 2 of these 4 windows before committing to any site.', variant: 'teal' },
      { type: 'h2', text: 'Competition analysis for restaurants' },
      { type: 'p', text: 'Restaurant competition analysis requires more nuance than café competition analysis because concept differentiation matters more. Four Italian restaurants within 300 metres is a problem. One Italian, one Thai, one burger bar and one Japanese within 300 metres of your Italian concept is a different situation — they are all competing for dinner dollars but not directly competing for your specific customer.' },
      { type: 'h2', text: 'Demographics: building your revenue model from suburb data' },
      { type: 'callout', icon: '📊', title: 'Restaurant price point by suburb income', body: 'Median income $130K+: Fine dining ($100–$180pp) viable\\nMedian income $90K–$130K: Modern casual ($60–$100pp) strong\\nMedian income $70K–$90K: Casual dining ($35–$65pp) optimal\\nMedian income $55K–$70K: Value casual ($20–$40pp) necessary\\nMedian income below $55K: QSR and takeaway dominant', variant: 'teal' },
      { type: 'h2', text: 'The 5-year lease trap: how to protect yourself' },
      { type: 'callout', icon: '⚠️', title: 'Non-negotiable lease protections for restaurants', body: 'Personal guarantee: cap at 6–12 months rent, not the full lease term\\n12-month break option: at year 2 or 3 with 3 months notice\\nRent review method: CPI-linked, not fixed percentage above CPI\\nFit-out contribution: negotiate minimum $50K for a raw shell\\nExclusion rights: prevent landlord leasing adjacent space to direct competitor', variant: 'red' },
      { type: 'h2', text: 'FAQ: restaurant location analysis' },
      { type: 'h3', text: 'What is the most important factor in choosing a restaurant location?' },
      { type: 'p', text: 'Access and visibility combined with rent affordability consistently predict success more reliably than raw foot traffic alone. A slightly lower foot traffic location with easy parking, good visibility and affordable rent will outperform a high foot traffic location with difficult access and punishing rent.' },
      { type: 'h3', text: 'How many competitors is too many for a restaurant location?' },
      { type: 'p', text: 'Direct competitors (same cuisine, similar price point) — more than 3 within 300 metres is a yellow flag. More than 5 is a red flag unless foot traffic is genuinely exceptional. General dining competition at higher density can actually indicate a strong dining precinct.' },
      { type: 'h3', text: 'Should I open a restaurant on a main road or a side street?' },
      { type: 'p', text: 'Main road locations offer visibility and walk-past traffic but typically carry higher rent and through-traffic character. Side street locations often have lower rent, a more local customer base, and a more intimate atmosphere that suits casual and fine dining.' },
    ],
  },
`

let content = fs.readFileSync('lib/blog-posts.ts', 'utf8')

const insertBefore = 'export const POST_LIST'
const idx = content.indexOf(insertBefore)
if (idx === -1) { console.log('❌ POST_LIST not found'); process.exit(1) }

const before = content.slice(0, idx)
const insertPoint = before.lastIndexOf('\n\n')

content = content.slice(0, insertPoint) + '\n\n' + newPosts.trim() + '\n\n' + content.slice(insertPoint + 2)
fs.writeFileSync('lib/blog-posts.ts', content)

const slugs = [
  'how-to-choose-cafe-location-australia',
  'business-feasibility-study-template-australia',
  'commercial-rent-affordability-calculator-australia',
  'best-suburbs-open-cafe-melbourne',
  'opening-restaurant-location-analysis-guide',
]
for (const s of slugs) console.log(s + ':', content.includes("'" + s + "'") ? '✅' : '❌')
console.log('Total posts:', (content.match(/slug: '/g) || []).length)
