// lib/suburb-data.ts
// Phase 2 programmatic SEO — suburb-level pages
// These target high-intent searches like "best suburb to open cafe perth"

export const SUBURB_SLUGS = [
  // Perth
  'subiaco','mount-lawley','leederville','fremantle','northbridge',
  'victoria-park','cottesloe','claremont','joondalup','midland',
  // Sydney
  'surry-hills','newtown','glebe','balmain','manly',
  'parramatta','chatswood','bondi-junction','leichhardt','marrickville',
  // Melbourne
  'fitzroy','brunswick','richmond','south-yarra','st-kilda',
  'prahran','collingwood','carlton','hawthorn','footscray',
  // Brisbane
  'new-farm','west-end','paddington-brisbane','teneriffe','fortitude-valley',
  'bulimba','red-hill','ascot','woolloongabba','toowong',
  // Adelaide
  'norwood','unley','glenelg','prospect','henley-beach',
  // Gold Coast
  'burleigh-heads','broadbeach','miami-gold-coast','palm-beach-qld','coolangatta',
  // Canberra
  'braddon','kingston-act','manuka','dickson','belconnen',
  // Newcastle
  'darby-street','honeysuckle','hamilton-nsw','merewether','carrington',
] as const

export type SuburbSlug = typeof SUBURB_SLUGS[number]

export interface SuburbData {
  slug: SuburbSlug
  name: string
  city: string
  citySlug: string
  state: string
  description: string
  vibe: string
  demographics: string
  footTraffic: 'Very High' | 'High' | 'Moderate' | 'Low'
  rentRange: string
  topStreets: string[]
  bestFor: string[]        // business types this suburb suits best
  notBestFor: string[]     // business types that struggle here
  demandScores: {
    cafes: number
    restaurants: number
    retail: number
    gyms: number
    takeaway: number
  }
  keyInsight: string
  nearbyAnchors: string[]  // nearby landmarks / traffic drivers
  population: string
  avgIncome: string
  parkingEase: 'Easy' | 'Moderate' | 'Difficult' | 'Very Difficult'
}

export const SUBURBS: SuburbData[] = [
  // ─── PERTH ───────────────────────────────────────────────────────────────

  {
    slug: 'subiaco',
    name: 'Subiaco',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Subiaco is one of Perth\'s most affluent and walkable inner suburbs. Home to a dense café strip along Rokeby Road, a large hospital precinct, and high-income residents. The area rewards quality operators with a loyal repeat customer base.',
    vibe: 'Affluent, health-conscious, professional',
    demographics: 'Young professionals, families, medical workers, university students',
    footTraffic: 'High',
    rentRange: '$3,500–$7,500/month',
    topStreets: ['Rokeby Road', 'Hay Street', 'Bagot Road'],
    bestFor: ['cafes', 'restaurants', 'gyms', 'retail'],
    notBestFor: ['takeaway'],
    demandScores: { cafes: 88, restaurants: 82, retail: 78, gyms: 85, takeaway: 65 },
    keyInsight: 'Subiaco\'s Rokeby Road is Perth\'s most established café strip. Strong brunch culture and high incomes mean customers spend freely. Gyms thrive due to the health-conscious demographic near Sir Charles Gairdner Hospital.',
    nearbyAnchors: ['Sir Charles Gairdner Hospital', 'Subiaco Oval precinct', 'UWA campus nearby'],
    population: '~18,000',
    avgIncome: '$88,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'mount-lawley',
    name: 'Mount Lawley',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Mount Lawley is Perth\'s hipster heartland — a thriving café culture hub along Beaufort Street with an eclectic mix of independent businesses, bars, and restaurants. Known for creativity, community, and a strong local-first ethos.',
    vibe: 'Creative, indie, café culture, nightlife',
    demographics: 'Artists, young professionals, students, long-term locals',
    footTraffic: 'High',
    rentRange: '$2,200–$5,500/month',
    topStreets: ['Beaufort Street', 'Lord Street'],
    bestFor: ['cafes', 'restaurants', 'retail'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 91, restaurants: 85, retail: 74, gyms: 62, takeaway: 78 },
    keyInsight: 'Beaufort Street is Perth\'s most celebrated independent food strip. Lower rents than Subiaco with equal or higher café demand. Ideal for first-time operators who want community support and lower risk.',
    nearbyAnchors: ['Astor Theatre', 'TAFE WA Perth', 'Highgate border'],
    population: '~10,000',
    avgIncome: '$72,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'leederville',
    name: 'Leederville',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Leederville is a compact, vibrant inner suburb with Oxford Street as its beating heart. Known for its weekend market buzz, boutique retail, and quality café scene. High foot traffic on weekends driven by the Leederville Markets.',
    vibe: 'Weekend buzz, boutique, foodie',
    demographics: 'Young professionals, creatives, families',
    footTraffic: 'High',
    rentRange: '$2,500–$6,000/month',
    topStreets: ['Oxford Street', 'Newcastle Street'],
    bestFor: ['cafes', 'retail', 'takeaway'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 85, restaurants: 78, retail: 81, gyms: 58, takeaway: 80 },
    keyInsight: 'Leederville benefits from strong weekend foot traffic from the markets and cinema precinct. Oxford Street has genuine street life — rare in Perth. Great for operators who can capture both the morning café crowd and evening dining.',
    nearbyAnchors: ['Leederville Markets', 'Luna Palace Cinema', 'Edith Cowan University nearby'],
    population: '~5,000',
    avgIncome: '$75,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'fremantle',
    name: 'Fremantle',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Fremantle is Perth\'s most distinctive suburb — a heritage port town with a thriving food market, arts scene, and strong tourism. The famous Fremantle Markets drive massive weekend foot traffic, making it excellent for hospitality and retail.',
    vibe: 'Maritime heritage, artisan, bohemian, tourist-friendly',
    demographics: 'Tourists, artists, students, long-term locals, backpackers',
    footTraffic: 'Very High',
    rentRange: '$2,500–$7,000/month',
    topStreets: ['South Terrace', 'High Street', 'Market Street'],
    bestFor: ['cafes', 'restaurants', 'retail', 'takeaway'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 84, restaurants: 86, retail: 82, gyms: 55, takeaway: 88 },
    keyInsight: 'Fremantle Markets draw tens of thousands every weekend creating exceptional retail and hospitality conditions. Weekday trade is quieter — operators must plan for this seasonal rhythm. Tourism adds a reliable second revenue stream.',
    nearbyAnchors: ['Fremantle Markets', 'Fremantle Port', 'Notre Dame University', 'Esplanade Park'],
    population: '~28,000',
    avgIncome: '$65,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'northbridge',
    name: 'Northbridge',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Northbridge is Perth\'s primary entertainment and dining precinct, directly north of the CBD. It houses the highest concentration of restaurants, bars, and cafés in Western Australia, with strong evening trade year-round.',
    vibe: 'Entertainment, nightlife, multicultural dining',
    demographics: 'CBD workers, tourists, students, nightlife crowd',
    footTraffic: 'Very High',
    rentRange: '$3,500–$10,000/month',
    topStreets: ['James Street', 'William Street', 'Lake Street'],
    bestFor: ['restaurants', 'cafes', 'takeaway'],
    notBestFor: ['retail', 'gyms'],
    demandScores: { cafes: 82, restaurants: 92, retail: 65, gyms: 60, takeaway: 88 },
    keyInsight: 'Northbridge has the highest restaurant density in WA but also the highest sales volumes. Evening trade is the key revenue driver — operators need a strong dinner offering. The weekend brunch market is also growing rapidly.',
    nearbyAnchors: ['Perth Cultural Centre', 'WACA ground nearby', 'Perth CBD border', 'RAC Arena'],
    population: '~5,000 residents',
    avgIncome: '$68,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'victoria-park',
    name: 'Victoria Park',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Victoria Park\'s Albany Highway strip is one of Perth\'s most underrated food corridors, offering excellent value rents with strong local patronage. The suburb is gentrifying quickly with rising incomes and younger demographic influx.',
    vibe: 'Emerging, multicultural, value-driven, gentrifying',
    demographics: 'Young families, first-home buyers, multicultural community',
    footTraffic: 'Moderate',
    rentRange: '$1,800–$4,500/month',
    topStreets: ['Albany Highway', 'Shepperton Road'],
    bestFor: ['cafes', 'takeaway', 'restaurants'],
    notBestFor: ['retail', 'gyms'],
    demandScores: { cafes: 79, restaurants: 76, retail: 62, gyms: 65, takeaway: 82 },
    keyInsight: 'Victoria Park offers the best value opportunity in inner Perth. Rents are 40–50% lower than Subiaco but demand is growing fast. Ideal for operators who want to establish before the suburb fully gentrifies.',
    nearbyAnchors: ['Curtin University nearby', 'Perth Stadium', 'Burswood precinct'],
    population: '~14,000',
    avgIncome: '$70,000',
    parkingEase: 'Easy',
  },
  {
    slug: 'cottesloe',
    name: 'Cottesloe',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Cottesloe is Perth\'s premium beach suburb with high property values and an affluent, active lifestyle community. Napoleon Street is the main commercial strip, supporting quality cafés, boutiques and health-focused businesses.',
    vibe: 'Beach lifestyle, affluent, health-conscious',
    demographics: 'High-income families, retirees, beach professionals',
    footTraffic: 'Moderate',
    rentRange: '$3,000–$7,000/month',
    topStreets: ['Napoleon Street', 'Marine Parade'],
    bestFor: ['cafes', 'retail', 'gyms'],
    notBestFor: ['takeaway', 'restaurants'],
    demandScores: { cafes: 86, restaurants: 72, retail: 78, gyms: 82, takeaway: 58 },
    keyInsight: 'Cottesloe\'s Napoleon Street supports premium pricing and strong brunch trade. The beach lifestyle drives high gym and activewear retail demand. Weekend trade from beach visitors provides a significant revenue boost from October to April.',
    nearbyAnchors: ['Cottesloe Beach', 'Indiana Restaurant', 'Cottesloe Civic Centre'],
    population: '~7,000',
    avgIncome: '$98,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'claremont',
    name: 'Claremont',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Claremont is Perth\'s upmarket western suburbs shopping hub, anchored by Claremont Quarter shopping centre. St Quentin Avenue and Bay View Terrace support a vibrant café and restaurant precinct serving an affluent local population.',
    vibe: 'Upmarket, shopping district, heritage charm',
    demographics: 'Affluent professionals, private school families, western suburbs retirees',
    footTraffic: 'High',
    rentRange: '$3,500–$8,000/month',
    topStreets: ['St Quentin Avenue', 'Bay View Terrace'],
    bestFor: ['retail', 'cafes', 'restaurants'],
    notBestFor: ['takeaway'],
    demandScores: { cafes: 84, restaurants: 80, retail: 89, gyms: 76, takeaway: 60 },
    keyInsight: 'Claremont Quarter anchors one of Perth\'s strongest retail precincts. The nearby café strip benefits enormously from shopping centre foot traffic. Premium pricing is well-supported — this is one of the few Perth locations where average spend rivals Sydney.',
    nearbyAnchors: ['Claremont Quarter Shopping Centre', 'Claremont Showgrounds', 'Lake Claremont'],
    population: '~9,000',
    avgIncome: '$95,000',
    parkingEase: 'Easy',
  },
  {
    slug: 'joondalup',
    name: 'Joondalup',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Joondalup is Perth\'s northern strategic centre — a planned city with a major hospital, university, and shopping precinct. The area serves a large catchment of northern suburbs residents and is experiencing strong population growth.',
    vibe: 'Planned urban centre, family-oriented, growing',
    demographics: 'Families, students, healthcare workers, northern suburbs professionals',
    footTraffic: 'High',
    rentRange: '$2,500–$6,000/month',
    topStreets: ['Boas Avenue', 'Reid Promenade', 'Central Walk'],
    bestFor: ['takeaway', 'cafes', 'retail', 'gyms'],
    notBestFor: [],
    demandScores: { cafes: 78, restaurants: 75, retail: 83, gyms: 80, takeaway: 85 },
    keyInsight: 'Joondalup\'s large catchment population and anchor institutions (hospital, university, train station) create strong all-day trade. Takeaway and quick service food performs exceptionally well. Less competition than inner Perth, with growing demand.',
    nearbyAnchors: ['Joondalup Health Campus', 'ECU Joondalup', 'Lakeside Joondalup Shopping City', 'Train station'],
    population: '~14,000 (large catchment)',
    avgIncome: '$72,000',
    parkingEase: 'Easy',
  },
  {
    slug: 'midland',
    name: 'Midland',
    city: 'Perth',
    citySlug: 'perth',
    state: 'WA',
    description: 'Midland is Perth\'s eastern hub, recently transformed by the new St John of God Hospital and Midland Gate expansion. A formerly underserved market now attracting significant investment and population growth.',
    vibe: 'Emerging, working class, hospital precinct',
    demographics: 'Working families, hospital staff, outer suburbs residents',
    footTraffic: 'Moderate',
    rentRange: '$1,500–$4,000/month',
    topStreets: ['Great Northern Highway', 'Yelverton Drive'],
    bestFor: ['takeaway', 'cafes', 'gyms'],
    notBestFor: ['retail', 'restaurants'],
    demandScores: { cafes: 70, restaurants: 65, retail: 68, gyms: 72, takeaway: 82 },
    keyInsight: 'Midland is Perth\'s best value emerging opportunity. The new hospital brings thousands of staff and visitors daily. Rents are among the lowest in the Perth metropolitan area while demand is rising sharply. Strong opportunity for takeaway and café operators.',
    nearbyAnchors: ['St John of God Midland Hospital', 'Midland Gate Shopping Centre', 'Midland Train Station'],
    population: '~21,000',
    avgIncome: '$62,000',
    parkingEase: 'Easy',
  },

  // ─── SYDNEY ───────────────────────────────────────────────────────────────

  {
    slug: 'surry-hills',
    name: 'Surry Hills',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Surry Hills is Sydney\'s most celebrated food and café suburb, packed into a dense grid of terrace houses and converted warehouses. Crown Street is one of Australia\'s finest dining streets, attracting food-obsessed locals and visitors.',
    vibe: 'Foodie, creative, hip, inner-city',
    demographics: 'Young professionals, creatives, hospitality workers, foodies',
    footTraffic: 'Very High',
    rentRange: '$6,000–$16,000/month',
    topStreets: ['Crown Street', 'Bourke Street', 'Cleveland Street'],
    bestFor: ['cafes', 'restaurants'],
    notBestFor: ['gyms', 'retail'],
    demandScores: { cafes: 95, restaurants: 94, retail: 72, gyms: 68, takeaway: 85 },
    keyInsight: 'Surry Hills has arguably Australia\'s most competitive hospitality market. Rents are high but sales volumes match. Success requires a distinctive offering — generic cafés and restaurants will not last. Ideal for experienced operators with a strong concept.',
    nearbyAnchors: ['Sydney CBD border', 'Central Station', 'Moore Park entertainment precinct'],
    population: '~14,000',
    avgIncome: '$85,000',
    parkingEase: 'Very Difficult',
  },
  {
    slug: 'newtown',
    name: 'Newtown',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Newtown\'s King Street is Sydney\'s most eclectic and independent commercial strip — a 2km corridor of cafés, ethnic restaurants, vintage retail, and bars. The suburb has a strong alternative culture and fiercely loyal local customer base.',
    vibe: 'Alternative, student, multicultural, independent',
    demographics: 'Students, artists, LGBTQ+ community, academics, long-term renters',
    footTraffic: 'Very High',
    rentRange: '$4,000–$10,000/month',
    topStreets: ['King Street', 'Enmore Road'],
    bestFor: ['cafes', 'restaurants', 'retail', 'takeaway'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 92, restaurants: 90, retail: 85, gyms: 62, takeaway: 90 },
    keyInsight: 'King Street has one of the highest pedestrian counts in Sydney. Lower rents than Surry Hills with strong demand. The independent culture means locals actively avoid chains — a huge advantage for small owner-operators.',
    nearbyAnchors: ['University of Sydney', 'RPA Hospital', 'Enmore Theatre', 'Newtown Station'],
    population: '~14,000',
    avgIncome: '$72,000',
    parkingEase: 'Very Difficult',
  },
  {
    slug: 'glebe',
    name: 'Glebe',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Glebe is a charming inner-west suburb adjacent to the University of Sydney. Glebe Point Road supports a lively café and restaurant scene with a bohemian character. Strong student and academic patronage creates reliable weekday trade.',
    vibe: 'Bohemian, academic, relaxed, community-focused',
    demographics: 'Students, academics, long-term inner-west residents',
    footTraffic: 'High',
    rentRange: '$3,500–$8,000/month',
    topStreets: ['Glebe Point Road', 'Broadway'],
    bestFor: ['cafes', 'takeaway', 'restaurants'],
    notBestFor: ['retail', 'gyms'],
    demandScores: { cafes: 87, restaurants: 82, retail: 68, gyms: 60, takeaway: 88 },
    keyInsight: 'Proximity to the University of Sydney creates consistent foot traffic from students and staff. Glebe Point Road benefits from both the student lunch rush and local evening diners. Rent is noticeably lower than Newtown for similar demand.',
    nearbyAnchors: ['University of Sydney', 'Fish Market', 'Wentworth Park'],
    population: '~8,500',
    avgIncome: '$68,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'balmain',
    name: 'Balmain',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Balmain is an affluent peninsula suburb with a strong village identity. Darling Street supports excellent cafés, restaurants and boutiques serving an increasingly wealthy residential base. Weekend trade is particularly strong.',
    vibe: 'Village feel, gentrified, affluent, community',
    demographics: 'Affluent professionals, families, long-term residents',
    footTraffic: 'High',
    rentRange: '$4,000–$9,000/month',
    topStreets: ['Darling Street', 'Beattie Street'],
    bestFor: ['cafes', 'retail', 'restaurants'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 88, restaurants: 84, retail: 82, gyms: 65, takeaway: 62 },
    keyInsight: 'Balmain\'s peninsula location creates a captive local customer base. Residents shop and eat locally out of loyalty and convenience. High incomes support premium pricing across all categories.',
    nearbyAnchors: ['Balmain Markets', 'Mort Bay Park', 'Dawn Fraser Baths'],
    population: '~14,000',
    avgIncome: '$95,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'manly',
    name: 'Manly',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Manly is Sydney\'s iconic Northern Beaches hub, combining strong tourist traffic with an affluent permanent population. The Corso and beachfront strips support excellent hospitality trade, particularly in summer.',
    vibe: 'Beach lifestyle, tourist, vibrant, summer-peak',
    demographics: 'Tourists, backpackers, affluent beach families, surfers',
    footTraffic: 'Very High',
    rentRange: '$5,000–$14,000/month',
    topStreets: ['The Corso', 'Sydney Road', 'Pittwater Road'],
    bestFor: ['cafes', 'restaurants', 'takeaway', 'retail'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 90, restaurants: 88, retail: 84, gyms: 65, takeaway: 88 },
    keyInsight: 'Manly has two customer segments — locals who spend all year and tourists who concentrate in summer. Operators who can serve both thrive. The ferry from the CBD brings a premium Sydney demographic every weekend.',
    nearbyAnchors: ['Manly Beach', 'Manly Ferry Wharf', 'Manly Oval', 'Shelly Beach'],
    population: '~15,000',
    avgIncome: '$90,000',
    parkingEase: 'Very Difficult',
  },
  {
    slug: 'parramatta',
    name: 'Parramatta',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Parramatta is Sydney\'s second CBD, the economic and administrative capital of Western Sydney. It is one of Australia\'s fastest growing commercial centres with massive infrastructure investment and a growing corporate workforce.',
    vibe: 'Commercial hub, multicultural, fast-growing',
    demographics: 'Office workers, government employees, Western Sydney families, migrants',
    footTraffic: 'Very High',
    rentRange: '$4,000–$12,000/month',
    topStreets: ['Church Street', 'Eat Street (Wigram)', 'Macquarie Street'],
    bestFor: ['takeaway', 'restaurants', 'cafes', 'retail'],
    notBestFor: [],
    demandScores: { cafes: 85, restaurants: 88, retail: 86, gyms: 78, takeaway: 93 },
    keyInsight: 'Parramatta\'s lunch trade is among the strongest in Australia. Office workers create enormous weekday demand. The Eat Street precinct has become a genuine dining destination. Strong opportunity for operators who can handle high volumes.',
    nearbyAnchors: ['Parramatta CBD', 'Westfield Parramatta', 'Western Sydney Stadium', 'Train station'],
    population: '~32,000',
    avgIncome: '$72,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'chatswood',
    name: 'Chatswood',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Chatswood is Sydney\'s North Shore commercial hub and a major dining destination, particularly known for its exceptional Asian cuisine precinct. High-density residential towers feed consistent foot traffic to the retail and food strips.',
    vibe: 'Asian-influenced, commercial, dense, foodie',
    demographics: 'Asian-Australian community, North Shore professionals, apartment residents',
    footTraffic: 'Very High',
    rentRange: '$5,000–$15,000/month',
    topStreets: ['Victoria Avenue', 'Anderson Street', 'Help Street'],
    bestFor: ['restaurants', 'takeaway', 'retail', 'cafes'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 84, restaurants: 93, retail: 90, gyms: 68, takeaway: 92 },
    keyInsight: 'Chatswood\'s Asian food scene creates exceptional restaurant demand. The combination of high residential density and Westfield anchors means consistent trade across all hours. Competition is high but sales volumes are higher.',
    nearbyAnchors: ['Westfield Chatswood', 'Chatswood Chase', 'Metro station', 'Mandarin Centre'],
    population: '~27,000',
    avgIncome: '$82,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'bondi-junction',
    name: 'Bondi Junction',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Bondi Junction is the commercial heart of Sydney\'s Eastern Suburbs — a major transport hub anchored by Westfield and surrounded by affluent residential catchment. Strong all-day trade from commuters and local residents.',
    vibe: 'Commercial transport hub, affluent catchment',
    demographics: 'Eastern Suburbs professionals, Westfield shoppers, commuters',
    footTraffic: 'Very High',
    rentRange: '$5,500–$16,000/month',
    topStreets: ['Oxford Street', 'Spring Street', 'Bronte Road'],
    bestFor: ['cafes', 'retail', 'takeaway', 'restaurants'],
    notBestFor: [],
    demandScores: { cafes: 88, restaurants: 86, retail: 93, gyms: 82, takeaway: 90 },
    keyInsight: 'One of Sydney\'s most reliable trading locations. The combination of train station, bus interchange, and Westfield creates best-in-class foot traffic. Rents are high but returns justify the investment for well-run operations.',
    nearbyAnchors: ['Westfield Bondi Junction', 'Bondi Junction Station', 'Eastern Suburbs corridor'],
    population: '~14,000',
    avgIncome: '$92,000',
    parkingEase: 'Easy',
  },
  {
    slug: 'leichhardt',
    name: 'Leichhardt',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Leichhardt is Sydney\'s "Little Italy" — Norton Street is a famous Italian dining corridor with a strong local café culture. The suburb has undergone significant gentrification while maintaining its distinct Italian heritage character.',
    vibe: 'Italian heritage, village, community, gentrifying',
    demographics: 'Italian-Australian community, young families, inner-west professionals',
    footTraffic: 'High',
    rentRange: '$3,500–$8,000/month',
    topStreets: ['Norton Street', 'Marion Street'],
    bestFor: ['restaurants', 'cafes', 'retail'],
    notBestFor: ['gyms', 'takeaway'],
    demandScores: { cafes: 86, restaurants: 88, retail: 76, gyms: 62, takeaway: 72 },
    keyInsight: 'Norton Street\'s Italian identity creates a genuine dining destination effect. People travel from across Sydney specifically to dine here. A food concept that complements rather than competes with Italian heritage works best.',
    nearbyAnchors: ['Palace Norton Street Cinema', 'Leichhardt Markets', 'Petersham border'],
    population: '~16,000',
    avgIncome: '$78,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'marrickville',
    name: 'Marrickville',
    city: 'Sydney',
    citySlug: 'sydney',
    state: 'NSW',
    description: 'Marrickville is one of Sydney\'s most exciting emerging food suburbs. The area has undergone remarkable transformation over the past decade, with a thriving warehouse café scene, craft breweries, and multicultural food corridor.',
    vibe: 'Emerging, warehouse cool, multicultural, craft',
    demographics: 'Creatives, young renters, Greek-Australian community, gentrifiers',
    footTraffic: 'High',
    rentRange: '$2,500–$7,000/month',
    topStreets: ['Marrickville Road', 'Illawarra Road', 'Sydenham Road'],
    bestFor: ['cafes', 'restaurants', 'retail', 'takeaway'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 88, restaurants: 86, retail: 78, gyms: 62, takeaway: 85 },
    keyInsight: 'Marrickville offers Newtown-level demand at 30% lower rents. The suburb is a genuine discovery destination for Sydney foodies. Warehouse conversions create unique venue opportunities not available in other suburbs.',
    nearbyAnchors: ['Sydenham Station', 'Marrickville Metro', 'Sydney Park', 'Airport nearby'],
    population: '~21,000',
    avgIncome: '$72,000',
    parkingEase: 'Moderate',
  },

  // ─── MELBOURNE ────────────────────────────────────────────────────────────

  {
    slug: 'fitzroy',
    name: 'Fitzroy',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'Fitzroy is the birthplace of Melbourne\'s legendary café culture. Brunswick Street remains one of Australia\'s most celebrated food and nightlife corridors, drawing discerning diners and coffee obsessives from across the city.',
    vibe: 'Artisan, bohemian, café-obsessed, creative industry',
    demographics: 'Creatives, design professionals, students, Melbourne food cognoscenti',
    footTraffic: 'Very High',
    rentRange: '$5,000–$12,000/month',
    topStreets: ['Brunswick Street', 'Smith Street', 'Johnston Street'],
    bestFor: ['cafes', 'restaurants', 'retail'],
    notBestFor: ['gyms', 'takeaway'],
    demandScores: { cafes: 97, restaurants: 93, retail: 86, gyms: 62, takeaway: 78 },
    keyInsight: 'Fitzroy is where Melbourne\'s café culture was born and where its standards are highest. Mediocre coffee and food will fail instantly. For exceptional operators with a genuine concept, there is no better location in Australia.',
    nearbyAnchors: ['Melbourne Museum nearby', 'RMIT campus', 'Fitzroy Gardens'],
    population: '~10,000',
    avgIncome: '$78,000',
    parkingEase: 'Very Difficult',
  },
  {
    slug: 'brunswick',
    name: 'Brunswick',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'Brunswick is Melbourne\'s multicultural heartland, known for its Middle Eastern dining strip on Sydney Road and a thriving independent music and café scene. More affordable than Fitzroy with equally passionate food culture.',
    vibe: 'Multicultural, alternative, student, vinyl-and-coffee',
    demographics: 'Students, artists, Middle Eastern community, young renters',
    footTraffic: 'High',
    rentRange: '$2,500–$6,500/month',
    topStreets: ['Sydney Road', 'Lygon Street extension'],
    bestFor: ['cafes', 'restaurants', 'retail', 'takeaway'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 91, restaurants: 88, retail: 80, gyms: 65, takeaway: 86 },
    keyInsight: 'Brunswick offers Melbourne-standard café culture at dramatically lower rents than Fitzroy. Sydney Road\'s Middle Eastern food culture creates a genuine destination effect. Strong student and artist demographic means consistent patronage.',
    nearbyAnchors: ['RMIT Brunswick campus', 'Barkly Square', 'Multiple tram routes'],
    population: '~19,000',
    avgIncome: '$65,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'richmond',
    name: 'Richmond',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'Richmond is Melbourne\'s Vietnamese restaurant hub on Victoria Street, combined with a thriving Church Street café and boutique retail precinct. The suburb benefits from MCG and stadiums driving massive event day trade.',
    vibe: 'Vietnamese culinary hub, sport-adjacent, gentrifying',
    demographics: 'Vietnamese-Australian community, professionals, foodies, sports crowds',
    footTraffic: 'High',
    rentRange: '$3,500–$9,000/month',
    topStreets: ['Victoria Street', 'Church Street', 'Swan Street'],
    bestFor: ['restaurants', 'cafes', 'takeaway', 'retail'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 88, restaurants: 93, retail: 80, gyms: 68, takeaway: 90 },
    keyInsight: 'Richmond\'s Victoria Street is Australia\'s best Vietnamese restaurant precinct, drawing diners citywide. MCG event days create exceptional revenue spikes. Church Street supports quality café and boutique trade for the professional residential base.',
    nearbyAnchors: ['MCG', 'AAMI Park', 'Richmond Station', 'Bridge Road shopping'],
    population: '~25,000',
    avgIncome: '$78,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'south-yarra',
    name: 'South Yarra',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'South Yarra is Melbourne\'s most glamorous inner suburb. Chapel Street is Australia\'s premier fashion retail strip, while Toorak Road supports some of Melbourne\'s finest restaurants. High incomes and aspirational demographics drive premium spending.',
    vibe: 'Glamorous, fashion-forward, premium dining, aspirational',
    demographics: 'Affluent professionals, fashion industry, young executives',
    footTraffic: 'Very High',
    rentRange: '$6,000–$18,000/month',
    topStreets: ['Chapel Street', 'Toorak Road', 'Commercial Road'],
    bestFor: ['retail', 'restaurants', 'cafes'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 88, restaurants: 91, retail: 96, gyms: 75, takeaway: 65 },
    keyInsight: 'South Yarra commands Melbourne\'s highest retail rents outside the CBD but also its highest retail sales per sqm. The premium demographic actively seeks quality and is highly brand-conscious. Only operators with strong visual identity and product quality should consider this location.',
    nearbyAnchors: ['Como Centre', 'South Yarra Station', 'The Jam Factory', 'Fawkner Park'],
    population: '~21,000',
    avgIncome: '$95,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'st-kilda',
    name: 'St Kilda',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'St Kilda combines Melbourne beach culture with a vibrant nightlife and café scene. Acland Street is famous for its continental cake shops and Sunday market buzz. Strong tourist trade supplements the large local resident and hostel population.',
    vibe: 'Beach, bohemian, tourist, nightlife, multicultural',
    demographics: 'Backpackers, young internationals, long-term locals, weekend tourists',
    footTraffic: 'Very High',
    rentRange: '$4,000–$10,000/month',
    topStreets: ['Acland Street', 'Fitzroy Street', 'Carlisle Street'],
    bestFor: ['cafes', 'restaurants', 'takeaway', 'retail'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 90, restaurants: 88, retail: 82, gyms: 68, takeaway: 88 },
    keyInsight: 'St Kilda\'s weekend foot traffic is among Melbourne\'s highest. The tourist and backpacker population adds a reliable international customer base. Fitzroy Street nightlife drives strong late-night food demand not seen in most other Melbourne suburbs.',
    nearbyAnchors: ['St Kilda Beach', 'Luna Park', 'St Kilda Pier', 'Palais Theatre'],
    population: '~20,000',
    avgIncome: '$68,000',
    parkingEase: 'Very Difficult',
  },
  {
    slug: 'prahran',
    name: 'Prahran',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'Prahran is Chapel Street\'s affordable southern extension, home to Prahran Market — Melbourne\'s finest fresh produce market. Strong café and gourmet food culture serves an affluent yet unpretentious residential base.',
    vibe: 'Market culture, gourmet, independent, less showy than South Yarra',
    demographics: 'Affluent food lovers, market regulars, young families',
    footTraffic: 'High',
    rentRange: '$3,500–$8,500/month',
    topStreets: ['Chapel Street (southern)', 'Commercial Road', 'High Street'],
    bestFor: ['cafes', 'retail', 'restaurants'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 90, restaurants: 85, retail: 84, gyms: 70, takeaway: 68 },
    keyInsight: 'Prahran Market drives some of Melbourne\'s best weekend café trade. Market proximity is a massive advantage — operators near the market benefit from Saturday and Sunday morning rushes that outperform weekday trade.',
    nearbyAnchors: ['Prahran Market', 'Prahran Station', 'Windsor border'],
    population: '~11,000',
    avgIncome: '$85,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'collingwood',
    name: 'Collingwood',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'Collingwood is Melbourne\'s converted warehouse district — a hub for creative industry, breweries, and destination dining. Smith Street rivals Brunswick Street for café culture with a more industrial-chic aesthetic.',
    vibe: 'Industrial-cool, creative, brewery culture, artisan',
    demographics: 'Designers, tech workers, creative industry, young professionals',
    footTraffic: 'High',
    rentRange: '$3,500–$9,000/month',
    topStreets: ['Smith Street', 'Johnston Street', 'Oxford Street'],
    bestFor: ['cafes', 'restaurants', 'retail'],
    notBestFor: ['gyms', 'takeaway'],
    demandScores: { cafes: 92, restaurants: 90, retail: 82, gyms: 65, takeaway: 78 },
    keyInsight: 'Collingwood\'s warehouse conversions offer unique venue formats impossible to find elsewhere. The creative industry workforce creates strong weekday lunch and coffee trade. Evenings are driven by destination diners attracted by the suburb\'s brewery and bar culture.',
    nearbyAnchors: ['MCG nearby', 'Collingwood Arts Precinct', 'Abbotsford Convent'],
    population: '~8,500',
    avgIncome: '$72,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'carlton',
    name: 'Carlton',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'Carlton\'s Lygon Street is Australia\'s original Italian dining strip and one of Melbourne\'s most visited food precincts. Proximity to the University of Melbourne ensures a large, consistent student customer base.',
    vibe: 'Italian heritage, academic, traditional dining strip',
    demographics: 'Italian-Australian community, university students, academics, tourists',
    footTraffic: 'Very High',
    rentRange: '$4,500–$11,000/month',
    topStreets: ['Lygon Street', 'Grattan Street', 'Swanston Street'],
    bestFor: ['restaurants', 'cafes', 'retail'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 88, restaurants: 92, retail: 78, gyms: 60, takeaway: 85 },
    keyInsight: 'Lygon Street is a true dining destination with national brand recognition. Proximity to the University of Melbourne and Melbourne Museum creates exceptional daytime trade. The Italian heritage identity means diners have high expectations for quality.',
    nearbyAnchors: ['University of Melbourne', 'Melbourne Museum', 'Carlton Gardens', 'Royal Exhibition Building'],
    population: '~16,000',
    avgIncome: '$70,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'hawthorn',
    name: 'Hawthorn',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'Hawthorn is one of Melbourne\'s wealthiest suburbs, with Glenferrie Road as its vibrant village shopping strip. Strong café and boutique retail trade serves an affluent residential base of professionals and established families.',
    vibe: 'Affluent village, old money, boutique, heritage',
    demographics: 'Established professionals, private school families, retirees',
    footTraffic: 'High',
    rentRange: '$4,000–$9,000/month',
    topStreets: ['Glenferrie Road', 'Auburn Road', 'Church Street'],
    bestFor: ['cafes', 'retail', 'restaurants', 'gyms'],
    notBestFor: ['takeaway'],
    demandScores: { cafes: 88, restaurants: 84, retail: 88, gyms: 82, takeaway: 62 },
    keyInsight: 'Hawthorn\'s private school cluster and high-income households create reliable premium spending. Swinburne University adds a student demographic. The suburb rewards quality and presentation — presentation matters as much as product here.',
    nearbyAnchors: ['Swinburne University', 'Hawthorn Station', 'Glenferrie Station', 'Riverside Golf Club'],
    population: '~22,000',
    avgIncome: '$96,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'footscray',
    name: 'Footscray',
    city: 'Melbourne',
    citySlug: 'melbourne',
    state: 'VIC',
    description: 'Footscray is Melbourne\'s most exciting inner-west suburb — a multicultural powerhouse with Vietnamese, African, and Latin food scenes. Rapidly gentrifying with a wave of café openings, yet maintaining affordable rents and raw energy.',
    vibe: 'Multicultural, raw, gentrifying, underrated foodie hub',
    demographics: 'Vietnamese-Australian community, African community, new gentrifiers, students',
    footTraffic: 'High',
    rentRange: '$1,800–$5,000/month',
    topStreets: ['Hopkins Street', 'Nicholson Street', 'Leeds Street'],
    bestFor: ['restaurants', 'cafes', 'takeaway'],
    notBestFor: ['retail', 'gyms'],
    demandScores: { cafes: 86, restaurants: 90, retail: 68, gyms: 62, takeaway: 88 },
    keyInsight: 'Footscray offers Melbourne\'s best opportunity for first-time operators. Rents are 50–60% lower than Fitzroy with growing demand. The multicultural food culture creates genuine destination dining. The gentrification wave is early-stage — now is the time to enter.',
    nearbyAnchors: ['Footscray Station', 'VU Footscray campus', 'Maribyrnong River', 'CBD 6km'],
    population: '~16,000',
    avgIncome: '$60,000',
    parkingEase: 'Easy',
  },

  // ─── BRISBANE ─────────────────────────────────────────────────────────────

  {
    slug: 'new-farm',
    name: 'New Farm',
    city: 'Brisbane',
    citySlug: 'brisbane',
    state: 'QLD',
    description: 'New Farm is Brisbane\'s most sophisticated café and dining suburb. Merthyr Road and Brunswick Street Village create a charming, walkable food precinct serving an affluent riverside community. Often compared to Melbourne\'s inner-suburb culture.',
    vibe: 'Sophisticated, riverside, café culture, affluent',
    demographics: 'Young professionals, gay community, affluent downsizers, foodies',
    footTraffic: 'High',
    rentRange: '$3,000–$7,500/month',
    topStreets: ['Brunswick Street', 'Merthyr Road', 'James Street'],
    bestFor: ['cafes', 'restaurants', 'retail'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 92, restaurants: 88, retail: 82, gyms: 68, takeaway: 68 },
    keyInsight: 'New Farm has Brisbane\'s strongest café culture and is the benchmark for quality in the city. James Street has evolved into a premium retail and restaurant destination. High incomes and walkability create the conditions for sustained hospitality success.',
    nearbyAnchors: ['New Farm Park', 'Powerhouse Brisbane', 'James Street precinct', 'City Cat ferry'],
    population: '~12,000',
    avgIncome: '$88,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'west-end',
    name: 'West End',
    city: 'Brisbane',
    citySlug: 'brisbane',
    state: 'QLD',
    description: 'West End is Brisbane\'s bohemian hub — a multicultural, alternative suburb with a thriving café scene, Saturday markets, and strong creative community. Boundary Street is the main commercial strip with excellent independent food culture.',
    vibe: 'Bohemian, multicultural, indie, market culture',
    demographics: 'Students, artists, Greek-Australian community, young renters',
    footTraffic: 'High',
    rentRange: '$2,500–$6,000/month',
    topStreets: ['Boundary Street', 'Hardgrave Road', 'Melbourne Street'],
    bestFor: ['cafes', 'restaurants', 'retail', 'takeaway'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 90, restaurants: 86, retail: 78, gyms: 62, takeaway: 84 },
    keyInsight: 'West End offers New Farm-level café culture at 30% lower rents. The Saturday markets drive exceptional weekend foot traffic. Strong student and creative demographic means loyal, repeat patronage for quality independent operators.',
    nearbyAnchors: ['Davies Park Saturday Markets', 'Boundary Street Markets', 'South Bank nearby', 'QUT Kelvin Grove'],
    population: '~13,000',
    avgIncome: '$68,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'paddington-brisbane',
    name: 'Paddington',
    city: 'Brisbane',
    citySlug: 'brisbane',
    state: 'QLD',
    description: 'Brisbane\'s Paddington is a charming hilltop suburb with a vibrant café and boutique retail strip along Given Terrace and Latrobe Terrace. Gentrified Queenslanders house affluent professionals who support quality local businesses.',
    vibe: 'Leafy, boutique, brunch culture, local charm',
    demographics: 'Affluent professionals, young families, boutique shoppers',
    footTraffic: 'Moderate',
    rentRange: '$2,500–$6,000/month',
    topStreets: ['Given Terrace', 'Latrobe Terrace', 'Enoggera Terrace'],
    bestFor: ['cafes', 'retail', 'restaurants'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 87, restaurants: 82, retail: 84, gyms: 68, takeaway: 62 },
    keyInsight: 'Paddington rewards quality with intense loyalty. The community actively supports local over chain businesses. Weekend brunch trade is particularly strong. Lower volumes than New Farm but higher margins due to premium pricing tolerance.',
    nearbyAnchors: ['Suncorp Stadium (Lang Park)', 'Rosalie Village', 'Milton corridor'],
    population: '~7,000',
    avgIncome: '$85,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'teneriffe',
    name: 'Teneriffe',
    city: 'Brisbane',
    citySlug: 'brisbane',
    state: 'QLD',
    description: 'Teneriffe is Brisbane\'s converted woolstore precinct — luxury apartment living in heritage buildings beside the river. A growing café and restaurant scene serves a high-income, design-conscious resident base.',
    vibe: 'Heritage industrial conversion, luxury, riverside',
    demographics: 'High-income professionals, design industry, apartment dwellers',
    footTraffic: 'Moderate',
    rentRange: '$3,000–$7,000/month',
    topStreets: ['Florence Street', 'Commercial Road', 'Vernon Terrace'],
    bestFor: ['cafes', 'restaurants', 'retail'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 86, restaurants: 84, retail: 78, gyms: 72, takeaway: 62 },
    keyInsight: 'Teneriffe has Brisbane\'s highest income per capita residential base. The woolstore heritage creates unique venue formats in converted spaces. Demand is growing as more luxury apartments are completed. Early operators benefit from first-mover advantage.',
    nearbyAnchors: ['Gasworks Plaza', 'City Cat ferry', 'New Farm border', 'Fortitude Valley nearby'],
    population: '~5,000',
    avgIncome: '$105,000',
    parkingEase: 'Easy',
  },
  {
    slug: 'fortitude-valley',
    name: 'Fortitude Valley',
    city: 'Brisbane',
    citySlug: 'brisbane',
    state: 'QLD',
    description: 'Fortitude Valley is Brisbane\'s premier entertainment and nightlife precinct, directly adjacent to the CBD. The James Street fashion and dining corridor coexists with the Brunswick Street nightclub strip, creating diverse business opportunities.',
    vibe: 'Nightlife, entertainment, fashion, creative industry',
    demographics: 'Nightlife crowd, creative industry, CBD workers, tourists',
    footTraffic: 'Very High',
    rentRange: '$4,000–$11,000/month',
    topStreets: ['James Street', 'Ann Street', 'Brunswick Street'],
    bestFor: ['restaurants', 'cafes', 'retail', 'takeaway'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 85, restaurants: 91, retail: 87, gyms: 65, takeaway: 88 },
    keyInsight: 'Fortitude Valley has Brisbane\'s highest evening trade volumes. James Street\'s fashion precinct draws affluent shoppers who then dine nearby. Weekend foot traffic rivals Sydney inner suburbs. Strong all-day opportunity for the right operator.',
    nearbyAnchors: ['Brisbane Showgrounds', 'RNA Showgrounds', 'CBD border', 'Brunswick Street Mall'],
    population: '~8,000',
    avgIncome: '$72,000',
    parkingEase: 'Difficult',
  },
  {
    slug: 'bulimba',
    name: 'Bulimba',
    city: 'Brisbane',
    citySlug: 'brisbane',
    state: 'QLD',
    description: 'Bulimba\'s Oxford Street is one of Brisbane\'s best village shopping strips — a tree-lined corridor of cafés, restaurants, and boutiques serving an extremely affluent riverside residential base.',
    vibe: 'Upmarket village, river lifestyle, family affluence',
    demographics: 'Affluent families, professionals, river residents',
    footTraffic: 'Moderate',
    rentRange: '$2,500–$6,500/month',
    topStreets: ['Oxford Street', 'Wynnum Road'],
    bestFor: ['cafes', 'retail', 'restaurants'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 88, restaurants: 84, retail: 85, gyms: 72, takeaway: 62 },
    keyInsight: 'Bulimba is Brisbane\'s best undiscovered village strip. Incomes are among Brisbane\'s highest and the community is intensely loyal to local businesses. Lower profile than New Farm means rents are competitive for the demographic quality.',
    nearbyAnchors: ['City Cat ferry at Hawthorne', 'Bulimba Memorial Park', 'Churchie school'],
    population: '~6,000',
    avgIncome: '$95,000',
    parkingEase: 'Moderate',
  },

  // ─── ADELAIDE ─────────────────────────────────────────────────────────────

  {
    slug: 'norwood',
    name: 'Norwood',
    city: 'Adelaide',
    citySlug: 'adelaide',
    state: 'SA',
    description: 'Norwood\'s The Parade is one of Adelaide\'s finest shopping and dining streets — a vibrant strip of cafés, restaurants, and boutiques that punches well above its weight. Strong local community patronage creates reliable trade.',
    vibe: 'Village elegance, café culture, boutique shopping',
    demographics: 'Affluent professionals, families, long-term Adelaide residents',
    footTraffic: 'High',
    rentRange: '$2,000–$5,500/month',
    topStreets: ['The Parade', 'George Street'],
    bestFor: ['cafes', 'retail', 'restaurants'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 86, restaurants: 82, retail: 84, gyms: 68, takeaway: 65 },
    keyInsight: 'The Parade is one of Australia\'s best value commercial streets. Adelaide rents are dramatically lower than east coast equivalents while demand and demographics are comparable. Exceptional ROI potential for quality operators.',
    nearbyAnchors: ['The Parade precinct', 'Norwood Oval', 'Norwood Morialta High School nearby'],
    population: '~7,000',
    avgIncome: '$78,000',
    parkingEase: 'Easy',
  },
  {
    slug: 'unley',
    name: 'Unley',
    city: 'Adelaide',
    citySlug: 'adelaide',
    state: 'SA',
    description: 'Unley Road and King William Road are Adelaide\'s premium café and boutique corridors. Unley\'s residential base is among South Australia\'s wealthiest, creating strong demand for quality hospitality and specialty retail.',
    vibe: 'Premium, affluent, heritage homes, café culture',
    demographics: 'High-income professionals, established families, retirees',
    footTraffic: 'Moderate',
    rentRange: '$2,000–$5,000/month',
    topStreets: ['Unley Road', 'King William Road', 'Leader Street'],
    bestFor: ['cafes', 'retail', 'gyms'],
    notBestFor: ['takeaway', 'restaurants'],
    demandScores: { cafes: 85, restaurants: 78, retail: 86, gyms: 80, takeaway: 58 },
    keyInsight: 'King William Road is arguably Adelaide\'s most premium retail strip, with average incomes among South Australia\'s highest. Boutique retail and café operators find exceptional returns with comparatively low rents versus Sydney or Melbourne equivalents.',
    nearbyAnchors: ['Hyde Park area', 'Goodwood Road', 'Unley Shopping Centre'],
    population: '~5,000',
    avgIncome: '$92,000',
    parkingEase: 'Easy',
  },
  {
    slug: 'glenelg',
    name: 'Glenelg',
    city: 'Adelaide',
    citySlug: 'adelaide',
    state: 'SA',
    description: 'Glenelg is Adelaide\'s beach suburb and number one tourist destination, connected to the city by Australia\'s only remaining original tram route. Jetty Road is the commercial spine, supporting strong hospitality and retail trade boosted by tourism.',
    vibe: 'Beach tourism, heritage tram, summer peak, family-friendly',
    demographics: 'Tourists, summer families, Adelaide beach residents',
    footTraffic: 'High',
    rentRange: '$2,000–$5,500/month',
    topStreets: ['Jetty Road', 'Moseley Square'],
    bestFor: ['cafes', 'takeaway', 'restaurants', 'retail'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 82, restaurants: 82, retail: 80, gyms: 60, takeaway: 85 },
    keyInsight: 'Glenelg offers strong summer trading with Adelaide\'s highest tourist numbers. The tram connection to the CBD means year-round weekday trade from city workers. Rents are competitive and the market is less saturated than Sydney or Melbourne beach suburbs.',
    nearbyAnchors: ['Glenelg Beach', 'Holdfast Shores', 'Adelaide tram terminus', 'Stamford Grand'],
    population: '~20,000',
    avgIncome: '$72,000',
    parkingEase: 'Moderate',
  },

  // ─── GOLD COAST ───────────────────────────────────────────────────────────

  {
    slug: 'burleigh-heads',
    name: 'Burleigh Heads',
    city: 'Gold Coast',
    citySlug: 'gold-coast',
    state: 'QLD',
    description: 'Burleigh Heads has become the Gold Coast\'s coolest suburb — a surf culture hub with a thriving café scene that attracts quality-conscious locals and visitors who prefer it to the tourist excess of Surfers Paradise.',
    vibe: 'Surf culture, artisan café, Instagram-worthy, lifestyle',
    demographics: 'Surfers, health-conscious locals, young professionals, foodies',
    footTraffic: 'High',
    rentRange: '$2,500–$7,000/month',
    topStreets: ['James Street', 'Gold Coast Highway', 'The Esplanade'],
    bestFor: ['cafes', 'retail', 'restaurants'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 92, restaurants: 86, retail: 82, gyms: 78, takeaway: 70 },
    keyInsight: 'Burleigh has overtaken Surfers Paradise as the Gold Coast\'s most desirable café and dining location. Health-conscious demographic means premium pricing is well-supported. Less tourist volatility than northern Gold Coast suburbs.',
    nearbyAnchors: ['Burleigh Beach', 'Burleigh Heads National Park', 'James Street Market'],
    population: '~12,000',
    avgIncome: '$72,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'broadbeach',
    name: 'Broadbeach',
    city: 'Gold Coast',
    citySlug: 'gold-coast',
    state: 'QLD',
    description: 'Broadbeach is the Gold Coast\'s dining and entertainment hub — a well-planned precinct with excellent café, restaurant, and nightlife density. The suburb benefits from The Star casino traffic and Pacific Fair shopping centre visitors.',
    vibe: 'Dining precinct, entertainment, weekend buzz',
    demographics: 'Tourists, Gold Coast locals, casino visitors, convention attendees',
    footTraffic: 'Very High',
    rentRange: '$3,000–$8,500/month',
    topStreets: ['Surf Parade', 'Albert Avenue', 'Oracle Boulevard'],
    bestFor: ['restaurants', 'cafes', 'takeaway', 'retail'],
    notBestFor: ['gyms'],
    demandScores: { cafes: 87, restaurants: 92, retail: 85, gyms: 68, takeaway: 90 },
    keyInsight: 'Broadbeach is the Gold Coast\'s most reliable commercial precinct. Casino and convention traffic creates consistent spending that insulates against seasonal fluctuation. Oracle Boulevard development has created a genuinely premium dining destination.',
    nearbyAnchors: ['The Star Gold Coast', 'Pacific Fair Shopping Centre', 'Gold Coast Convention Centre', 'Light Rail'],
    population: '~7,000',
    avgIncome: '$68,000',
    parkingEase: 'Easy',
  },

  // ─── CANBERRA ─────────────────────────────────────────────────────────────

  {
    slug: 'braddon',
    name: 'Braddon',
    city: 'Canberra',
    citySlug: 'canberra',
    state: 'ACT',
    description: 'Braddon has transformed from a light industrial suburb into Canberra\'s most vibrant café and dining precinct. Lonsdale Street is the beating heart, with quality coffee and food concepts serving the adjacent CBD workforce.',
    vibe: 'Trendy, café culture, laneways, progressive',
    demographics: 'Government workers, CBD professionals, creatives, students',
    footTraffic: 'High',
    rentRange: '$2,500–$6,500/month',
    topStreets: ['Lonsdale Street', 'Mort Street', 'Elouera Street'],
    bestFor: ['cafes', 'restaurants', 'retail'],
    notBestFor: ['gyms', 'takeaway'],
    demandScores: { cafes: 92, restaurants: 88, retail: 80, gyms: 70, takeaway: 78 },
    keyInsight: 'Braddon is Canberra\'s most exciting dining precinct and is still growing. Government workers have generous expense accounts and eat out frequently. Lower rents than Melbourne or Sydney with comparable food culture and higher average incomes.',
    nearbyAnchors: ['Canberra CBD border', 'Canberra Centre shopping mall', 'EPIC events centre', 'ANU nearby'],
    population: '~4,000',
    avgIncome: '$92,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'kingston-act',
    name: 'Kingston',
    city: 'Canberra',
    citySlug: 'canberra',
    state: 'ACT',
    description: 'Kingston is Canberra\'s original heritage suburb with a charming foreshore precinct on Lake Burley Griffin. Eyre Street and Kennedy Street support excellent café and restaurant trade for an affluent local and government employee base.',
    vibe: 'Heritage, waterfront, upmarket dining, government adjacent',
    demographics: 'Public service executives, diplomats, affluent professionals',
    footTraffic: 'Moderate',
    rentRange: '$2,500–$6,500/month',
    topStreets: ['Eyre Street', 'Kennedy Street', 'Kingston Foreshore'],
    bestFor: ['restaurants', 'cafes', 'retail'],
    notBestFor: ['takeaway', 'gyms'],
    demandScores: { cafes: 86, restaurants: 88, retail: 78, gyms: 68, takeaway: 62 },
    keyInsight: 'Kingston Foreshore is Canberra\'s premium dining destination, with waterfront restaurants commanding the highest prices in the city. The government and diplomatic demographic has significant entertainment budget. Weekend foreshore trade is excellent.',
    nearbyAnchors: ['Kingston Foreshore', 'Lake Burley Griffin', 'Old Bus Depot Markets', 'Department of Foreign Affairs'],
    population: '~5,000',
    avgIncome: '$98,000',
    parkingEase: 'Easy',
  },

  // ─── NEWCASTLE ────────────────────────────────────────────────────────────

  {
    slug: 'darby-street',
    name: 'Darby Street',
    city: 'Newcastle',
    citySlug: 'newcastle',
    state: 'NSW',
    description: 'Darby Street is Newcastle\'s premier café and boutique retail strip — a charming 1km corridor known for independent business culture and a strong local loyalty. The area has benefitted significantly from the city\'s urban renewal.',
    vibe: 'Independent, café culture, boutique, community',
    demographics: 'University students, young professionals, local families',
    footTraffic: 'Moderate',
    rentRange: '$1,500–$4,000/month',
    topStreets: ['Darby Street'],
    bestFor: ['cafes', 'retail', 'restaurants'],
    notBestFor: ['gyms', 'takeaway'],
    demandScores: { cafes: 88, restaurants: 80, retail: 82, gyms: 62, takeaway: 72 },
    keyInsight: 'Darby Street offers exceptional value for operators — comparable café culture to Melbourne inner suburbs at a fraction of the rent. Independent business culture means locals actively seek out non-chains. Strong social media profile increases discovery.',
    nearbyAnchors: ['University of Newcastle nearby', 'Newcastle Memorial Walk', 'Cooks Hill residential'],
    population: '~8,000 catchment',
    avgIncome: '$67,000',
    parkingEase: 'Moderate',
  },
  {
    slug: 'honeysuckle',
    name: 'Honeysuckle',
    city: 'Newcastle',
    citySlug: 'newcastle',
    state: 'NSW',
    description: 'Honeysuckle is Newcastle\'s new waterfront entertainment precinct — a transformed harbourside development with restaurants, bars, and event spaces. Strong weekend and event trade driven by proximity to Newcastle Harbour.',
    vibe: 'Waterfront entertainment, revitalised urban, event-driven',
    demographics: 'Newcastle professionals, weekend diners, event-goers',
    footTraffic: 'High',
    rentRange: '$2,500–$6,500/month',
    topStreets: ['Honeysuckle Drive', 'Wharf Road'],
    bestFor: ['restaurants', 'cafes', 'takeaway'],
    notBestFor: ['retail', 'gyms'],
    demandScores: { cafes: 82, restaurants: 88, retail: 68, gyms: 60, takeaway: 82 },
    keyInsight: 'Honeysuckle is Newcastle\'s growth story — from derelict railway yard to premium waterfront precinct. Event-driven trade from nearby entertainment venues creates revenue spikes. Still developing, meaning early operators secure the best sites and long-term lease terms.',
    nearbyAnchors: ['Newcastle Harbour', 'Newcastle Entertainment Centre', 'Newcastle train station', 'Hunter Street Mall'],
    population: '~2,000 (growing)',
    avgIncome: '$72,000',
    parkingEase: 'Easy',
  },
]

export function getSuburb(slug: string): SuburbData | undefined {
  return SUBURBS.find(s => s.slug === slug)
}

export function getSuburbsByCity(citySlug: string): SuburbData[] {
  return SUBURBS.filter(s => s.citySlug === citySlug)
}

export function getSuburbScore(suburb: SuburbData, type: string): number {
  const scores = suburb.demandScores as Record<string, number>
  return scores[type] ?? suburb.demandScores.cafes
}