export const dynamic = 'force-dynamic'
import Link from 'next/link'

const S = {
  brand: '#0F766E', brandLight: '#14B8A6', brandFaded: '#F0FDFA', brandBorder: '#99F6E4',
  n50: '#FAFAF9', n100: '#F5F5F4', n200: '#E7E5E4', n400: '#A8A29E', n500: '#78716C',
  n700: '#44403C', n800: '#292524', n900: '#1C1917', white: '#FFFFFF',
  emerald: '#059669', emeraldBg: '#ECFDF5', emeraldBdr: '#A7F3D0',
  amber: '#D97706', amberBg: '#FFFBEB',
  headerBg: '#0C1F1C', font: "'DM Sans', sans-serif",
}

const CHANGES = [
  {
    version: '1.3.0',
    date: 'March 2025',
    tag: 'Major update',
    tagColor: S.emerald,
    items: [
      { type: 'new', text: 'Self-contained analysis engine — no external workflow dependencies' },
      { type: 'new', text: 'Full financial model with 3-year projections and risk scenarios' },
      { type: 'new', text: 'SWOT analysis generated by GPT-4o-mini for every report' },
      { type: 'new', text: 'Terms of Service and Privacy Policy pages (Australian law compliant)' },
      { type: 'new', text: '404 page with on-brand design' },
      { type: 'improved', text: 'Onboarding map now uses srcDoc iframe — no more blank map bug' },
      { type: 'improved', text: 'Footer redesigned with logo, newsletter, social links and trust badges' },
      { type: 'fixed', text: 'Quota counter no longer resets on report deletion' },
      { type: 'fixed', text: 'Score ring now shows correct break-even data' },
    ],
  },
  {
    version: '1.2.0',
    date: 'February 2025',
    tag: 'New features',
    tagColor: S.brand,
    items: [
      { type: 'new', text: 'Dashboard with report history and status tracking' },
      { type: 'new', text: 'Forgot password and reset password flows' },
      { type: 'new', text: 'Admin quota override — admins can run unlimited reports' },
      { type: 'new', text: 'Public share links for reports' },
      { type: 'improved', text: 'Report page redesigned with waterfall chart and sensitivity analysis' },
      { type: 'improved', text: 'Competitor analysis expanded to include restaurants and gyms' },
      { type: 'fixed', text: 'SWOT no longer contradicts profitability verdict' },
      { type: 'fixed', text: 'Rent amount now correctly pulled from user input' },
    ],
  },
  {
    version: '1.1.0',
    date: 'January 2025',
    tag: 'Improvements',
    tagColor: S.amber,
    items: [
      { type: 'new', text: 'Pro Monthly ($19/mo) and Pro Lifetime ($49) plans' },
      { type: 'new', text: 'Stripe payment integration' },
      { type: 'new', text: 'Methodology page explaining data sources and scoring' },
      { type: 'improved', text: 'Landing page with animated product demo' },
      { type: 'improved', text: 'Onboarding flow simplified to 3 steps' },
      { type: 'fixed', text: 'Projection text no longer shows wrong year-on-year growth' },
    ],
  },
  {
    version: '1.0.0',
    date: 'December 2024',
    tag: 'Launch',
    tagColor: S.n500,
    items: [
      { type: 'new', text: 'Initial launch of Locatalyze' },
      { type: 'new', text: 'Location analysis with GO / CAUTION / NO verdict' },
      { type: 'new', text: 'Free plan with 3 reports' },
      { type: 'new', text: 'Competitor proximity data via Geoapify' },
      { type: 'new', text: 'ABS demographics lookup by suburb' },
      { type: 'new', text: 'Address geocoding via Nominatim' },
    ],
  },
]

const tagStyles: Record<string, { bg: string; color: string }> = {
  new:      { bg: S.emeraldBg,  color: S.emerald },
  improved: { bg: S.brandFaded, color: S.brand },
  fixed:    { bg: S.amberBg,    color: S.amber },
}
const tagLabels: Record<string, string> = { new: 'New', improved: 'Improved', fixed: 'Fixed' }

export default function ChangelogPage() {
  return (
    <>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
      <div style={{ minHeight: '100vh', background: S.n50, fontFamily: S.font }}>

        {/* Hero */}
        <div style={{ background: S.headerBg, padding: '60px 24px 48px', textAlign: 'center' }}>
          <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, textDecoration: 'none', marginBottom: 32 }}>
            <div style={{ width: 28, height: 28, borderRadius: 8, background: `linear-gradient(135deg,${S.brand},${S.brandLight})`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: 900, fontSize: 13 }}>L</div>
            <span style={{ fontWeight: 800, fontSize: 15, color: '#F9FAFB', letterSpacing: '-0.02em' }}>Locatalyze</span>
          </Link>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: 'rgba(15,118,110,0.15)', border: '1px solid rgba(15,118,110,0.3)', borderRadius: 20, padding: '4px 12px', fontSize: 11, fontWeight: 700, color: S.brandLight, letterSpacing: '1px', textTransform: 'uppercase', marginBottom: 16 }}>Changelog</div>
          <h1 style={{ fontSize: '36px', fontWeight: 800, color: '#F9FAFB', letterSpacing: '-0.5px', marginBottom: 12 }}>What's new</h1>
          <p style={{ fontSize: 15, color: '#9CA3AF' }}>Every update, improvement and fix — newest first.</p>
        </div>

        <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px' }}>
          {CHANGES.map((release, i) => (
            <div key={release.version} style={{ display: 'grid', gridTemplateColumns: '160px 1fr', gap: 32, marginBottom: 56 }}>
              {/* Left — version info */}
              <div style={{ paddingTop: 4 }}>
                <p style={{ fontSize: 18, fontWeight: 800, color: S.n900, letterSpacing: '-0.03em', marginBottom: 4 }}>v{release.version}</p>
                <p style={{ fontSize: 12, color: S.n400, marginBottom: 10 }}>{release.date}</p>
                <span style={{ display: 'inline-flex', alignItems: 'center', padding: '3px 10px', borderRadius: 20, fontSize: 11, fontWeight: 700, color: release.tagColor, background: release.tagColor + '18', border: `1px solid ${release.tagColor}30` }}>
                  {release.tag}
                </span>
              </div>

              {/* Right — items */}
              <div style={{ background: S.white, border: `1px solid ${S.n200}`, borderRadius: 14, padding: '20px 24px' }}>
                {release.items.map((item, j) => (
                  <div key={j} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, marginBottom: j < release.items.length - 1 ? 12 : 0 }}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', padding: '2px 8px', borderRadius: 6, fontSize: 10, fontWeight: 700, color: tagStyles[item.type].color, background: tagStyles[item.type].bg, flexShrink: 0, marginTop: 2 }}>
                      {tagLabels[item.type]}
                    </span>
                    <p style={{ fontSize: 13.5, color: S.n700, lineHeight: 1.6 }}>{item.text}</p>
                  </div>
                ))}
              </div>
            </div>
          ))}

          <div style={{ textAlign: 'center', padding: '20px', color: S.n400, fontSize: 13 }}>
            Have a feature request? <Link href="/contact" style={{ color: S.brand, fontWeight: 600, textDecoration: 'none' }}>Let us know →</Link>
          </div>
        </div>
      </div>
    </>
  )
}